# Generated by Django 5.0.4 on 2024-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0, max_length=1)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/client')),
            ],
        ),
    ]
